version: '3.4'

services:
    jupyterhub:
        #image: jupyterhub/jupyterhub:1.4.1
        image: npodewitz/jupyterhub:latest
        #build: ./jupyterhub-docker
        container_name: jupyterhub
        hostname: jupyterhub.${DOMAINNAME}
        restart: unless-stopped
        command: >
            jupyterhub -f /etc/jupyterhub/jupyterhub_config.py
        # healthcheck:
        #     test: ["CMD", "curl" , "--cacert", "/etc/ssl/root_ca.crt", "-f", "https://db-admin.podewitz.local:443"]
        #     interval: 30s
        #     timeout: 10s
        #     retries: 5
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./conf/jupyterhub/jupyterhub_config.py:/etc/jupyterhub/jupyterhub_config.py
        secrets:
            - source: etcd_client_ssl_key
              target: /etc/ssl/etcd_client.key
            - source: etcd_client_ssl_crt
              target: /etc/ssl/etcd_client.crt
            - source: root_ca_crt
              target: /etc/ssl/root_ca.crt
        env_file:
            - docker-compose.base.env
        environment:
            DOCKER_NOTEBOOK_IMAGE: "jupyter/scipy-notebook:lab-3.0.15"
            DOCKER_NETWORK_NAME: docker_composition_home_podewitz_local_net
            HUB_IP: jupyterhub
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.db-admin.rule=Host(`jupyter.${DOMAINNAME}`)"
            - "traefik.http.routers.db-admin.tls=true"
        networks:
            podewitz_local_net:
                aliases:
                    - jupyterhub.${DOMAINNAME}
                ipv4_address: 172.25.0.12
        depends_on:
            - etcd
            - ldap
            - reverse-proxy
            - db

